Repository AY2021S1-CS2113T-T12-1/tp, pull requests merged in 2020-10, with the labels that each got.

#68 Added Junit tests for academic parser.
  src/main/java/AcademicCommandParser.java
  src/main/java/academic/GradeBook.java
  src/main/java/academic/PersonBook.java
  src/test/java/AcademicParserTest.java
Labels: priority.High

#69 Added assertion for Addlinkcommand and removelinkcommand
  src/main/java/BookmarkParser.java
  src/main/java/Command.java
  src/main/java/bookmark/BookmarkUi.java
  src/main/java/bookmark/commands/AddLinkCommand.java
  src/main/java/bookmark/commands/BookmarkCommand.java
  src/main/java/bookmark/commands/RemoveLinkCommand.java
  src/main/java/exceptions/InvalidBookmarkLinkException.java
  src/main/java/exceptions/InvalidEmptyLinkException.java
  src/test/java/BookmarkParserTest.java
  src/test/java/bookmark/commands/AddLinkCommandTest.java
Labels: priority.High, type.Task

#70 Junit Test for timetable
  TimeTable.txt
  build.gradle
  src/main/java/AcademicCommandParser.java
  src/main/java/timetable/Duration.java
  src/main/java/timetable/TablePrinter.java
  src/main/java/timetable/TimeTableParser.java
  src/test/java/timetable/DateListTest.java
  src/test/java/timetable/DurationTest.java
  src/test/java/timetable/LessonTest.java
  src/test/java/timetable/TimeTableParserTest.java
Labels: priority.Low

#72 edit for style
  src/main/java/timetable/Activity.java
Labels: priority.Low

#73 Update Exceptions for bookmark features
  src/main/java/BookmarkParser.java
  src/main/java/Command.java
  src/main/java/bookmark/BookmarkUi.java
  src/main/java/bookmark/InvalidBookmarkCommandException.java
  src/main/java/bookmark/commands/AddLinkCommand.java
  src/main/java/bookmark/commands/BackCommand.java
  src/main/java/bookmark/commands/BookmarkCommand.java
  src/main/java/bookmark/commands/ChangeModeCommand.java
  src/main/java/bookmark/commands/ListCommand.java
  src/main/java/bookmark/commands/RemoveLinkCommand.java
  src/main/java/exceptions/EmptyBookmarkException.java
  src/main/java/exceptions/InvalidBookmarkException.java
  src/main/java/exceptions/InvalidBookmarkLinkException.java
  src/main/java/exceptions/InvalidEmptyLinkException.java
  src/test/java/BookmarkParserTest.java
  src/test/java/bookmark/commands/AddLinkCommandTest.java
  src/test/java/bookmark/commands/BackCommandTest.java
  src/test/java/bookmark/commands/ChangeModeCommandTest.java
  src/test/java/bookmark/commands/RemoveLinkCommandTest.java
Labels: priority.Medium

#76 Add setup for logging and some logging.
  StudyIt_Log.log
  src/main/java/BookmarkParser.java
  src/main/java/Command.java
  src/main/java/CommandParser.java
  src/main/java/ErrorMessage.java
  src/main/java/HelpMessage.java
  src/main/java/StudyIt.java
  src/main/java/StudyItLog.java
  src/main/java/Ui.java
Labels: priority.Medium

#83 Add assertions to user input and command/mode type identification
  src/main/java/Command.java
  src/main/java/Ui.java
  src/main/java/timetable/TimeTableParser.java
Labels: priority.High, type.Task

#93 Implemented local storage for academic.
  StudyIt_Log.log.1
  StudyIt_Log.log.1.lck
  data/academic.txt
  src/main/java/academic/AcademicCommandParser.java
  src/main/java/academic/AcademicStorage.java
  src/main/java/academic/Grade.java
  src/main/java/academic/Person.java
  src/main/java/studyit/Command.java
  src/main/java/studyit/StudyIt.java
Labels: priority.Medium

#111 Change logging file location and added logging to track commands
  .gitignore
  StudyIt_Log.log
  StudyIt_Log.log.1
  StudyIt_Log.log.1.lck
  StudyIt_Log.log.2
  StudyIt_Log.log.3
  StudyIt_Log.log.lck
  src/main/java/academic/AcademicRun.java
  src/main/java/bookmark/BookmarkRun.java
  src/main/java/bookmark/BookmarkStorage.java
  src/main/java/flashcard/FlashcardRun.java
  src/main/java/flashcard/FlashcardStorage.java
  src/main/java/studyit/Command.java
  src/main/java/studyit/StudyIt.java
  src/main/java/studyit/StudyItLog.java
  src/main/java/timetable/TimeTableParser.java
  src/main/java/timetable/TimeTableRun.java
  src/main/java/timetable/TimeTableStorage.java
Labels: type.Task

#114 added new feature to view link and reformat timetable
  StudyIt_Log.log.1
  StudyIt_Log.log.lck
  docs/TimeTable class diagram.drawio
  docs/flashcard class diagram
  docs/flashcard.drawio
  docs/timetable
  src/main/java/flashcard/Flashcard.java
  src/main/java/flashcard/FlashcardStorage.java
  src/main/java/timetable/Message.java
  src/main/java/timetable/TablePrinter.java
  src/main/java/timetable/TimeTableParser.java
  src/test/java/timetable/TimeTableParserTest.java
Labels: type.Epic
